spring:
  application:
    name: item-service
  #RDS
  datasource:
    url: jdbc:mysql://8vb0797i464v6o5evto.mysql.zhangbei.rds.aliyuncs.com/MyRds?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: lzp
    password: luzhaopeng
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 200
      initial-size: 100
      max-total: 2000
      max-wait-millis: 200
  #rabbitMQ
  rabbitmq:
    host: 39.99.222.128
    port: 5672
    username: lzp
    password: 123456
    template:
      retry:
        enabled: true
        initial-interval: 2s
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://myeureka:965448460@47.56.181.87:10000/eureka/
